In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("cleaned_titanic.csv")

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [4]:
df.groupby("Sex").mean(numeric_only=True)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
Sex,,,,,,,
female,431.028662,0.742038,2.159236,28.216730,0.694268,0.649682,44.479818
male,454.147314,0.188908,2.389948,30.505824,0.429809,0.235702,25.523893

In [5]:
df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [6]:
df.groupby(["Sex","Pclass"])["Survived"].mean()

Sex     Pclass
female  1         0.968085
        2         0.921053
        3         0.500000
male    1         0.368852
        2         0.157407
        3         0.135447
Name: Survived, dtype: float64

In [7]:
df.groupby("Sex")["Age"].agg(["mean","max","min"])

             mean   max   min
Sex
female  28.216730  63.0  0.75
male    30.505824  80.0  0.42

In [8]:
df.groupby("Pclass")["Fare"].mean().sort_values()

Pclass
3    13.675550
2    20.662183
1    84.154687
Name: Fare, dtype: float64

In [9]:
df["Age"].mean()

np.float64(29.69911764705882)

In [11]:
df["Embarked"].mode()

0    S
Name: Embarked, dtype: str